import { TEMPLATE_BUILDER_VIEW_TYPE } from '../views/TemplateBuilderView';
import { t } from '../lang/helpers';
import { GuideRegistry } from './GuideRegistry';
import {
  LAYOUT_BUILDER_ADD_WIDGET_BUTTON_TARGET_ID,
  LAYOUT_BUILDER_DEFAULT_TEMPLATE_SET_ACTION_ID,
  LAYOUT_BUILDER_DEFAULT_TEMPLATE_STAR_TARGET_ID,
  LAYOUT_BUILDER_DRC_BUILTIN_TEMPLATE_TARGET_ID,
  LAYOUT_BUILDER_SIDEBAR_TARGET_ID,
  LAYOUT_BUILDER_DRC_DUPLICATE_BUTTON_TARGET_ID,
  LAYOUT_BUILDER_EDITOR_MODE_BUTTON_TARGET_ID,
  LAYOUT_BUILDER_EDITOR_MODE_OPENED_ACTION_ID,
  LAYOUT_BUILDER_EDITOR_PANEL_TARGET_ID,
  LAYOUT_BUILDER_EMPTY_WIDGET_PICKER_TRIGGER_TARGET_ID,
  LAYOUT_BUILDER_MAIN_GUIDE_ID,
  LAYOUT_BUILDER_PREVIEW_TARGET_ID,
  LAYOUT_BUILDER_SAVE_BUTTON_TARGET_ID,
  LAYOUT_BUILDER_TEMPLATE_DUPLICATED_ACTION_ID,
  LAYOUT_BUILDER_TEMPLATE_SAVED_ACTION_ID,
  LAYOUT_BUILDER_WIDGET_ADDED_ACTION_ID,
  LAYOUT_BUILDER_WIDGET_LIBRARY_DOCS_TARGET_ID,
  LAYOUT_BUILDER_WIDGET_PICKER_OPENED_ACTION_ID,
  LAYOUT_BUILDER_WIDGET_PICKER_TARGET_ID,
  LAYOUT_BUILDER_WIDGET_SELECTED_ACTION_ID,
} from './layoutBuilderGuideIds';

export function registerLayoutBuilderMainGuide(
  guideRegistry: GuideRegistry
): void {
  guideRegistry.registerGuide({
    id: LAYOUT_BUILDER_MAIN_GUIDE_ID,
    viewType: TEMPLATE_BUILDER_VIEW_TYPE,
    version: 3,
    autoShow: true,
    priority: 100,
    initialStepId: 'intro',
    steps: [
      {
        id: 'intro',
        title: t('layoutBuilder.guide.intro.title'),
        description: t('layoutBuilder.guide.intro.description'),
        progression: 'manual',
        placement: 'center',
      },
      {
        id: 'sidebar-overview',
        title: t('layoutBuilder.guide.sidebar-overview.title'),
        description: t('layoutBuilder.guide.sidebar-overview.description'),
        progression: 'manual',
        targetId: LAYOUT_BUILDER_SIDEBAR_TARGET_ID,
        placement: 'right',
      },
      {
        id: 'pick-built-in-template',
        title: t('layoutBuilder.guide.pick-built-in.title'),
        description: t('layoutBuilder.guide.pick-built-in.description'),
        progression: 'manual',
        targetId: LAYOUT_BUILDER_DRC_BUILTIN_TEMPLATE_TARGET_ID,
        placement: 'right',
      },
      {
        id: 'duplicate-template',
        title: t('layoutBuilder.guide.duplicate.title'),
        description: t('layoutBuilder.guide.duplicate.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_DRC_DUPLICATE_BUTTON_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_TEMPLATE_DUPLICATED_ACTION_ID,
      },
      {
        id: 'preview-template',
        title: t('layoutBuilder.guide.preview-template.title'),
        description: t('layoutBuilder.guide.preview-template.description'),
        progression: 'manual',
        targetId: LAYOUT_BUILDER_PREVIEW_TARGET_ID,
        placement: 'right-top',
      },
      {
        id: 'switch-to-editor',
        title: t('layoutBuilder.guide.switch-to-editor.title'),
        description: t('layoutBuilder.guide.switch-to-editor.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_EDITOR_MODE_BUTTON_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_EDITOR_MODE_OPENED_ACTION_ID,
      },
      {
        id: 'editor-overview',
        title: t('layoutBuilder.guide.editor-overview.title'),
        description: t('layoutBuilder.guide.editor-overview.description'),
        progression: 'manual',
        targetId: LAYOUT_BUILDER_EDITOR_PANEL_TARGET_ID,
        placement: 'right-top',
      },
      {
        id: 'add-widget',
        title: t('layoutBuilder.guide.add-widget.title'),
        description: t('layoutBuilder.guide.add-widget.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_ADD_WIDGET_BUTTON_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_WIDGET_ADDED_ACTION_ID,
      },
      {
        id: 'open-widget-picker',
        title: t('layoutBuilder.guide.open-widget-picker.title'),
        description: t('layoutBuilder.guide.open-widget-picker.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_EMPTY_WIDGET_PICKER_TRIGGER_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_WIDGET_PICKER_OPENED_ACTION_ID,
      },
      {
        id: 'choose-widget',
        title: t('layoutBuilder.guide.choose-widget.title'),
        description: t('layoutBuilder.guide.choose-widget.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_WIDGET_PICKER_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_WIDGET_SELECTED_ACTION_ID,
        placement: 'right',
        skipIfTargetMissing: false,
      },
      {
        id: 'widget-library-docs',
        title: t('layoutBuilder.guide.widget-library-docs.title'),
        description: t('layoutBuilder.guide.widget-library-docs.description'),
        progression: 'manual',
        targetId: LAYOUT_BUILDER_WIDGET_LIBRARY_DOCS_TARGET_ID,
      },
      {
        id: 'save-template',
        title: t('layoutBuilder.guide.save-template.title'),
        description: t('layoutBuilder.guide.save-template.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_SAVE_BUTTON_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_TEMPLATE_SAVED_ACTION_ID,
      },
      {
        id: 'set-default-template',
        title: t('layoutBuilder.guide.set-default-template.title'),
        description: t('layoutBuilder.guide.set-default-template.description'),
        progression: 'action-required',
        targetId: LAYOUT_BUILDER_DEFAULT_TEMPLATE_STAR_TARGET_ID,
        requiredActionId: LAYOUT_BUILDER_DEFAULT_TEMPLATE_SET_ACTION_ID,
        placement: 'right',
      },
    ],
  });
}
