import { TRADE_LOG_VIEW_TYPE } from '../views/TradeLogView';
import { t } from '../lang/helpers';
import { GuideRegistry } from './GuideRegistry';
import {
  TRADE_LOG_BATCH_TOOLBAR_TARGET_ID,
  TRADE_LOG_COLUMN_SETTINGS_BUTTON_TARGET_ID,
  TRADE_LOG_COLUMN_SETTINGS_MODAL_TARGET_ID,
  TRADE_LOG_COLUMN_SETTINGS_OPENED_ACTION_ID,
  TRADE_LOG_FILTER_BUTTON_TARGET_ID,
  TRADE_LOG_FILTER_MODAL_OPENED_ACTION_ID,
  TRADE_LOG_FILTER_MODAL_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_ANNOTATION_OPENED_ACTION_ID,
  TRADE_LOG_IMAGE_GALLERY_ANNOTATION_PANEL_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_FILTER_SECTION_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_FULLSCREEN_ACTIONS_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_FULLSCREEN_OPENED_ACTION_ID,
  TRADE_LOG_IMAGE_GALLERY_GRID_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_GROUPING_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_MODE_BUTTON_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_SELECTED_ACTION_ID,
  TRADE_LOG_IMAGE_GALLERY_SIZE_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_SOURCE_SORT_TARGET_ID,
  TRADE_LOG_IMAGE_GALLERY_TAG_BUTTON_TARGET_ID,
  TRADE_LOG_MAIN_GUIDE_ID,
  TRADE_LOG_MULTI_SELECT_BUTTON_TARGET_ID,
  TRADE_LOG_MULTI_SELECT_ENABLED_ACTION_ID,
  TRADE_LOG_TABLE_HEADERS_TARGET_ID,
  TRADE_LOG_VIEW_SELECTOR_TARGET_ID,
} from './tradeLogGuideIds';

export const TRADE_LOG_MAIN_GUIDE_VERSION = 7;

export function registerTradeLogMainGuide(guideRegistry: GuideRegistry): void {
  guideRegistry.registerGuide({
    id: TRADE_LOG_MAIN_GUIDE_ID,
    viewType: TRADE_LOG_VIEW_TYPE,
    version: TRADE_LOG_MAIN_GUIDE_VERSION,
    autoShow: true,
    priority: 110,
    initialStepId: 'intro',
    steps: [
      {
        id: 'intro',
        title: t('tradelog.guide.intro.title'),
        description: t('tradelog.guide.intro.description'),
        progression: 'manual',
        placement: 'center',
      },
      {
        id: 'view-selector',
        title: t('tradelog.guide.view-selector.title'),
        description: t('tradelog.guide.view-selector.description'),
        progression: 'manual',
        targetId: TRADE_LOG_VIEW_SELECTOR_TARGET_ID,
      },
      {
        id: 'filters',
        title: t('tradelog.guide.filters.title'),
        description: t('tradelog.guide.filters.description'),
        progression: 'manual',
        targetId: TRADE_LOG_FILTER_BUTTON_TARGET_ID,
        requiredActionId: TRADE_LOG_FILTER_MODAL_OPENED_ACTION_ID,
      },
      {
        id: 'filter-modal',
        title: t('tradelog.guide.filter-modal.title'),
        description: t('tradelog.guide.filter-modal.description'),
        progression: 'manual',
        placement: 'right',
        targetId: TRADE_LOG_FILTER_MODAL_TARGET_ID,
        skipIfTargetMissing: false,
      },
      {
        id: 'sorting',
        title: t('tradelog.guide.sorting.title'),
        description: t('tradelog.guide.sorting.description'),
        progression: 'manual',
        targetId: TRADE_LOG_TABLE_HEADERS_TARGET_ID,
      },
      {
        id: 'multi-select',
        title: t('tradelog.guide.multi-select.title'),
        description: t('tradelog.guide.multi-select.description'),
        progression: 'action-required',
        targetId: TRADE_LOG_MULTI_SELECT_BUTTON_TARGET_ID,
        requiredActionId: TRADE_LOG_MULTI_SELECT_ENABLED_ACTION_ID,
      },
      {
        id: 'batch-actions',
        title: t('tradelog.guide.batch-actions.title'),
        description: t('tradelog.guide.batch-actions.description'),
        progression: 'manual',
        targetId: TRADE_LOG_BATCH_TOOLBAR_TARGET_ID,
      },
      {
        id: 'column-settings',
        title: t('tradelog.guide.column-settings.title'),
        description: t('tradelog.guide.column-settings.description'),
        progression: 'action-required',
        targetId: TRADE_LOG_COLUMN_SETTINGS_BUTTON_TARGET_ID,
        requiredActionId: TRADE_LOG_COLUMN_SETTINGS_OPENED_ACTION_ID,
      },
      {
        id: 'active-columns',
        title: t('tradelog.guide.active-columns.title'),
        description: t('tradelog.guide.active-columns.description'),
        progression: 'manual',
        placement: 'right',
        targetId: TRADE_LOG_COLUMN_SETTINGS_MODAL_TARGET_ID,
        skipIfTargetMissing: false,
      },
      {
        id: 'available-columns',
        title: t('tradelog.guide.available-columns.title'),
        description: t('tradelog.guide.available-columns.description'),
        progression: 'manual',
        placement: 'right',
        targetId: TRADE_LOG_COLUMN_SETTINGS_MODAL_TARGET_ID,
        skipIfTargetMissing: false,
      },
      {
        id: 'open-trades',
        title: t('tradelog.guide.open-trades.title'),
        description: t('tradelog.guide.open-trades.description'),
        progression: 'manual',
        placement: 'center',
      },
      {
        id: 'switch-to-gallery',
        title: t('tradelog.guide.switch-to-gallery.title'),
        description: t('tradelog.guide.switch-to-gallery.description'),
        progression: 'action-required',
        targetId: TRADE_LOG_IMAGE_GALLERY_MODE_BUTTON_TARGET_ID,
        requiredActionId: TRADE_LOG_IMAGE_GALLERY_SELECTED_ACTION_ID,
      },
      {
        id: 'gallery-source-sort',
        title: t('tradelog.guide.gallery-source-sort.title'),
        description: t('tradelog.guide.gallery-source-sort.description'),
        progression: 'manual',
        placement: 'left',
        targetId: TRADE_LOG_IMAGE_GALLERY_SOURCE_SORT_TARGET_ID,
      },
      {
        id: 'gallery-grouping',
        title: t('tradelog.guide.gallery-grouping.title'),
        description: t('tradelog.guide.gallery-grouping.description'),
        progression: 'manual',
        targetId: TRADE_LOG_IMAGE_GALLERY_GROUPING_TARGET_ID,
      },
      {
        id: 'gallery-size',
        title: t('tradelog.guide.gallery-size.title'),
        description: t('tradelog.guide.gallery-size.description'),
        progression: 'manual',
        targetId: TRADE_LOG_IMAGE_GALLERY_SIZE_TARGET_ID,
      },
      {
        id: 'gallery-filters',
        title: t('tradelog.guide.gallery-filters.title'),
        description: t('tradelog.guide.gallery-filters.description'),
        progression: 'manual',
        targetId: TRADE_LOG_FILTER_BUTTON_TARGET_ID,
        requiredActionId: TRADE_LOG_FILTER_MODAL_OPENED_ACTION_ID,
      },
      {
        id: 'gallery-filter-modal',
        title: t('tradelog.guide.gallery-filter-modal.title'),
        description: t('tradelog.guide.gallery-filter-modal.description'),
        progression: 'manual',
        placement: 'right',
        targetId: TRADE_LOG_IMAGE_GALLERY_FILTER_SECTION_TARGET_ID,
        skipIfTargetMissing: false,
      },
      {
        id: 'gallery-grid',
        title: t('tradelog.guide.gallery-grid.title'),
        description: t('tradelog.guide.gallery-grid.description'),
        progression: 'action-required',
        targetId: TRADE_LOG_IMAGE_GALLERY_GRID_TARGET_ID,
        requiredActionId: TRADE_LOG_IMAGE_GALLERY_FULLSCREEN_OPENED_ACTION_ID,
      },
      {
        id: 'gallery-fullscreen-actions',
        title: t('tradelog.guide.gallery-fullscreen-actions.title'),
        description: t('tradelog.guide.gallery-fullscreen-actions.description'),
        progression: 'manual',
        targetId: TRADE_LOG_IMAGE_GALLERY_FULLSCREEN_ACTIONS_TARGET_ID,
        skipIfTargetMissing: true,
      },
      {
        id: 'gallery-open-annotation',
        title: t('tradelog.guide.gallery-open-annotation.title'),
        description: t('tradelog.guide.gallery-open-annotation.description'),
        progression: 'action-required',
        targetId: TRADE_LOG_IMAGE_GALLERY_TAG_BUTTON_TARGET_ID,
        requiredActionId: TRADE_LOG_IMAGE_GALLERY_ANNOTATION_OPENED_ACTION_ID,
        skipIfTargetMissing: true,
      },
      {
        id: 'gallery-annotation-panel',
        title: t('tradelog.guide.gallery-annotation-panel.title'),
        description: t('tradelog.guide.gallery-annotation-panel.description'),
        progression: 'manual',
        targetId: TRADE_LOG_IMAGE_GALLERY_ANNOTATION_PANEL_TARGET_ID,
        skipIfTargetMissing: true,
      },
      {
        id: 'gallery-finish',
        title: t('tradelog.guide.gallery-finish.title'),
        description: t('tradelog.guide.gallery-finish.description'),
        progression: 'manual',
        placement: 'center',
      },
    ],
  });
}
